// SPDX-License-Identifier: Apache-2.0
// Generated by vLLM TileLang at ffd46bfab2128bb84146050e98b51a617c6575ab
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void mhc_fused_tilelang_kernel(const float* comb_mix, const float* post_mix, const bfloat16_t* residual_in, bfloat16_t* residual_out, float* rp_out, const float* weight_t, const bfloat16_t* x_in, float* yp_out, int num_tokens, int split_k);
extern "C" __global__ void __launch_bounds__(256, 1) mhc_fused_tilelang_kernel(const float* comb_mix, const float* post_mix, const bfloat16_t* residual_in, bfloat16_t* residual_out, float* rp_out, const float* weight_t, const bfloat16_t* x_in, float* yp_out, int num_tokens, int split_k) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float acc[2];
  float sqr[1];
  float pm[4];
  float cm[16];
  float new_r[4];
  float v = 0x0p+0f/*0.000000e+00*/;
  float v2 = 0x0p+0f/*0.000000e+00*/;
  float broadcast_var = 0x0p+0f/*0.000000e+00*/;
  *(float2*)(acc + 0) = make_float2(broadcast_var, broadcast_var);
  sqr[0] = 0x0p+0f/*0.000000e+00*/;
  cudaGridDependencySynchronize();
  if (((int)threadIdx.x) < 4) {
    ((float*)buf_dyn_shmem)[((int)threadIdx.x)] = post_mix[((((int64_t)((int)blockIdx.x)) * (int64_t)4) + ((int64_t)((int)threadIdx.x)))];
  }
  if (((int)threadIdx.x) < 16) {
    ((float*)buf_dyn_shmem)[(((int)threadIdx.x) + 4)] = comb_mix[((((int64_t)((int)blockIdx.x)) * (int64_t)16) + ((int64_t)((int)threadIdx.x)))];
  }
  __syncthreads();
  #pragma unroll
  for (int j = 0; j < 4; ++j) {
    pm[j] = ((float*)buf_dyn_shmem)[j];
  }
  #pragma unroll
  for (int j_1 = 0; j_1 < 4; ++j_1) {
    #pragma unroll
    for (int k = 0; k < 4; ++k) {
      cm[((k * 4) + j_1)] = ((float*)buf_dyn_shmem)[(((k * 4) + j_1) + 4)];
    }
  }
  for (int it = 0; it < ((4096 / split_k) >> 8); ++it) {
    #pragma unroll
    for (int j_2 = 0; j_2 < 4; ++j_2) {
      new_r[j_2] = (pm[j_2] * ((float)x_in[((((((int64_t)((int)blockIdx.x)) * (int64_t)4096) + (((int64_t)it) * (int64_t)256)) + (((int64_t)((int)blockIdx.z)) * ((int64_t)4096 / ((int64_t)split_k)))) + ((int64_t)((int)threadIdx.x)))]));
      #pragma unroll
      for (int k_1 = 0; k_1 < 4; ++k_1) {
        new_r[j_2] = (new_r[j_2] + (cm[((k_1 * 4) + j_2)] * ((float)residual_in[(((((((int64_t)((int)blockIdx.x)) * (int64_t)16384) + (((int64_t)k_1) * (int64_t)4096)) + (((int64_t)it) * (int64_t)256)) + (((int64_t)((int)blockIdx.z)) * ((int64_t)4096 / ((int64_t)split_k)))) + ((int64_t)((int)threadIdx.x)))])));
      }
    }
    if (((int)blockIdx.y) == 0) {
      #pragma unroll
      for (int j_3 = 0; j_3 < 4; ++j_3) {
        residual_out[(((((((int64_t)((int)blockIdx.x)) * (int64_t)16384) + (((int64_t)j_3) * (int64_t)4096)) + (((int64_t)it) * (int64_t)256)) + (((int64_t)((int)blockIdx.z)) * ((int64_t)4096 / ((int64_t)split_k)))) + ((int64_t)((int)threadIdx.x)))] = ((bfloat16_t)new_r[j_3]);
        sqr[0] = (sqr[0] + (new_r[j_3] * new_r[j_3]));
      }
    }
    #pragma unroll
    for (int n = 0; n < 2; ++n) {
      #pragma unroll
      for (int j_4 = 0; j_4 < 4; ++j_4) {
        acc[n] = (acc[n] + (weight_t[((((((((int64_t)((int)blockIdx.y)) * (int64_t)32768) + (((int64_t)n) * (int64_t)16384)) + (((int64_t)j_4) * (int64_t)4096)) + (((int64_t)it) * (int64_t)256)) + (((int64_t)((int)blockIdx.z)) * ((int64_t)4096 / ((int64_t)split_k)))) + ((int64_t)((int)threadIdx.x)))] * new_r[j_4]));
      }
    }
  }
  #pragma unroll
  for (int n_1 = 0; n_1 < 2; ++n_1) {
    acc[n_1] = tl::warp_reduce_sum(acc[n_1]);
  }
  if (((int)blockIdx.y) == 0) {
    sqr[0] = tl::warp_reduce_sum(sqr[0]);
  }
  if ((((int)threadIdx.x) % 32) == 0) {
    #pragma unroll
    for (int n_2 = 0; n_2 < 2; ++n_2) {
      ((float*)buf_dyn_shmem)[((((((int)threadIdx.x) >> 5) * 3) + n_2) + 20)] = acc[n_2];
    }
    if (((int)blockIdx.y) == 0) {
      ((float*)buf_dyn_shmem)[(((((int)threadIdx.x) >> 5) * 3) + 22)] = sqr[0];
    }
  }
  __syncthreads();
  if ((((int)threadIdx.x) >> 5) == 0) {
    if ((((int)threadIdx.x) & 31) < 2) {
      #pragma unroll
      for (int w = 0; w < 8; ++w) {
        v = (v + ((float*)buf_dyn_shmem)[(((w * 3) + (((int)threadIdx.x) & 31)) + 20)]);
      }
      yp_out[((((((int64_t)((int)blockIdx.x)) * (int64_t)24) + ((((int64_t)((int)blockIdx.z)) * ((int64_t)num_tokens)) * (int64_t)24)) + (((int64_t)((int)blockIdx.y)) * (int64_t)2)) + (((int64_t)((int)threadIdx.x)) & (int64_t)31))] = v;
    }
    if ((((int)blockIdx.y) == 0) && ((((int)threadIdx.x) % 32) == 0)) {
      #pragma unroll
      for (int w_1 = 0; w_1 < 8; ++w_1) {
        v2 = (v2 + ((float*)buf_dyn_shmem)[((w_1 * 3) + 22)]);
      }
      rp_out[((((int64_t)((int)blockIdx.z)) * ((int64_t)num_tokens)) + ((int64_t)((int)blockIdx.x)))] = v2;
    }
  }
cudaTriggerProgrammaticLaunchCompletion();
}

extern "C" __global__ void mhc_pre_big_fuse_with_norm_tilelang_kernel(
    float *, const float *, const float *, const float *, const float *,
    bfloat16_t *, const bfloat16_t *, float *, const bfloat16_t *, int);

extern "C" cudaError_t dsv4_vllm_mhc_post_pre_norm_batch(
    cudaStream_t stream, const float *comb_mix, const void *residual_in,
    const float *post_mix, const void *x_in, const float *weight_t,
    float *gemm_out_mul, float *gemm_out_sqrsum, void *residual_out,
    const float *hc_scale, const float *hc_base, void *layer_input,
    const void *norm_weight, int num_tokens) {
  if (num_tokens < 1) return cudaErrorInvalidValue;
  const int split_k = 8;
  mhc_fused_tilelang_kernel<<<dim3(num_tokens, 12, split_k), 256, 176, stream>>>(
      comb_mix, post_mix, static_cast<const bfloat16_t *>(residual_in),
      static_cast<bfloat16_t *>(residual_out), gemm_out_sqrsum, weight_t,
      static_cast<const bfloat16_t *>(x_in), gemm_out_mul, num_tokens,
      split_k);
  cudaError_t error = cudaGetLastError();
  if (error != cudaSuccess) return error;
  mhc_pre_big_fuse_with_norm_tilelang_kernel<<<num_tokens, 96, 29040, stream>>>(
      const_cast<float *>(comb_mix), gemm_out_mul, gemm_out_sqrsum, hc_base,
      hc_scale, static_cast<bfloat16_t *>(layer_input),
      static_cast<const bfloat16_t *>(norm_weight),
      const_cast<float *>(post_mix),
      static_cast<const bfloat16_t *>(residual_out), num_tokens);
  return cudaGetLastError();
}

extern "C" cudaError_t dsv4_vllm_mhc_post_pre_norm(
    cudaStream_t stream, const float *comb_mix, const void *residual_in,
    const float *post_mix, const void *x_in, const float *weight_t,
    float *gemm_out_mul, float *gemm_out_sqrsum, void *residual_out,
    const float *hc_scale, const float *hc_base, void *layer_input,
    const void *norm_weight) {
  return dsv4_vllm_mhc_post_pre_norm_batch(
      stream, comb_mix, residual_in, post_mix, x_in, weight_t, gemm_out_mul,
      gemm_out_sqrsum, residual_out, hc_scale, hc_base, layer_input,
      norm_weight, 1);
}


#include <math_constants.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void mhc_pre_big_fuse_with_norm_tilelang_kernel(float* comb_mix, const float* gemm_out_mul, const float* gemm_out_sqrsum, const float* hc_base, const float* hc_scale, bfloat16_t* layer_input, const bfloat16_t* norm_weight, float* post_mix, const bfloat16_t* residual, int num_tokens);
extern "C" __global__ void __launch_bounds__(96, 1) mhc_pre_big_fuse_with_norm_tilelang_kernel(float* comb_mix, const float* gemm_out_mul, const float* gemm_out_sqrsum, const float* hc_base, const float* hc_scale, bfloat16_t* layer_input, const bfloat16_t* norm_weight, float* post_mix, const bfloat16_t* residual, int num_tokens) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float mixes[1];
  float rms[1];
  float cm[1];
  float row_max[1];
  float row_sum[1];
  float col_sum[1];
  float sumsq_per_pos[16];
  float sumsq[1];
  float rsqrt_norm[1];
  float xl[64];
  float ol[16];
  bfloat16_t xs_local_cast[8];
  bfloat16_t xs_local_cast_1[8];
  bfloat16_t xs_local_cast_2[8];
  float w_local[16];
  float ol_1[16];
  bfloat16_t w_shared_local_cast_3[8];
  bfloat16_t output_shared_local_cast_4[8];
  bfloat16_t layer_input_local_cast_5[8];
  bfloat16_t w_shared_local_cast_6[8];
  bfloat16_t output_shared_local_cast_7[8];
  bfloat16_t layer_input_local_cast_8[8];
  bfloat16_t w_shared_local_cast_9[8];
  bfloat16_t output_shared_local_cast_10[8];
  bfloat16_t layer_input_local_cast_11[8];
  mixes[0] = 0x0p+0f/*0.000000e+00*/;
  rms[0] = 0x0p+0f/*0.000000e+00*/;
  cudaGridDependencySynchronize();
  for (int i_split = 0; i_split < 8; ++i_split) {
    rms[0] = (rms[0] + gemm_out_sqrsum[((((int64_t)i_split) * ((int64_t)num_tokens)) + ((int64_t)((int)blockIdx.x)))]);
  }
  rms[0] = rsqrtf(((rms[0] / 0x1p+14f/*1.638400e+04*/) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
  mixes[0] = 0x0p+0f/*0.000000e+00*/;
  for (int i_split_1 = 0; i_split_1 < 8; ++i_split_1) {
    mixes[0] = (mixes[0] + gemm_out_mul[(((((int64_t)((int)blockIdx.x)) * (int64_t)24) + ((((int64_t)i_split_1) * ((int64_t)num_tokens)) * (int64_t)24)) + (((int64_t)((int)threadIdx.x)) % (int64_t)24))]);
  }
  mixes[0] = (mixes[0] * rms[0]);
  if ((((int)threadIdx.x) / 24) == 0) {
    ((float*)buf_dyn_shmem)[(((int)threadIdx.x) % 24)] = mixes[0];
  }
  __syncthreads();
  if (((int)threadIdx.x) < 32) {
    if (((int)threadIdx.x) < 4) {
      post_mix[((((int64_t)((int)blockIdx.x)) * (int64_t)4) + ((int64_t)((int)threadIdx.x)))] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((((float*)buf_dyn_shmem)[(((int)threadIdx.x) + 4)] * hc_scale[1]) + hc_base[(((int)threadIdx.x) + 4)]))))) * 0x1p+1f/*2.000000e+00*/);
    }
    cm[0] = ((((float*)buf_dyn_shmem)[((((int)threadIdx.x) & 15) + 8)] * hc_scale[2]) + hc_base[((((int)threadIdx.x) & 15) + 8)]);
    row_max[0] = -CUDART_INF_F;
    row_max[0] = max(row_max[0], cm[0]);
    row_max[0] = tl::AllReduce<tl::MaxOp, 4, 1, 0, tl::NamedBarrier<32>>::run(row_max[0]);
    cm[0] = expf((cm[0] - row_max[0]));
    row_sum[0] = 0x0p+0f/*0.000000e+00*/;
    row_sum[0] = (row_sum[0] + cm[0]);
    row_sum[0] = tl::AllReduce<tl::SumOp, 4, 1, 0, tl::NamedBarrier<32>>::run(row_sum[0]);
    cm[0] = ((cm[0] / row_sum[0]) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/);
    col_sum[0] = 0x0p+0f/*0.000000e+00*/;
    col_sum[0] = (col_sum[0] + cm[0]);
    col_sum[0] = tl::AllReduce<tl::SumOp, 16, 4, 0, tl::NamedBarrier<32>>::run(col_sum[0]);
    cm[0] = (cm[0] / (col_sum[0] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
    for (int __1 = 0; __1 < 19; ++__1) {
      row_sum[0] = 0x0p+0f/*0.000000e+00*/;
      row_sum[0] = (row_sum[0] + cm[0]);
      row_sum[0] = tl::AllReduce<tl::SumOp, 4, 1, 0, tl::NamedBarrier<32>>::run(row_sum[0]);
      cm[0] = (cm[0] / (row_sum[0] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
      col_sum[0] = 0x0p+0f/*0.000000e+00*/;
      col_sum[0] = (col_sum[0] + cm[0]);
      col_sum[0] = tl::AllReduce<tl::SumOp, 16, 4, 0, tl::NamedBarrier<32>>::run(col_sum[0]);
      cm[0] = (cm[0] / (col_sum[0] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
    }
    if ((((int)threadIdx.x) >> 4) == 0) {
      comb_mix[((((int64_t)((int)blockIdx.x)) * (int64_t)16) + (((int64_t)((int)threadIdx.x)) & (int64_t)15))] = cm[0];
    }
  } else {
    if (((int)threadIdx.x) < 36) {
      ((float*)buf_dyn_shmem)[(((int)threadIdx.x) + 7224)] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((((float*)buf_dyn_shmem)[(((int)threadIdx.x) - 32)] * hc_scale[0]) + hc_base[(((int)threadIdx.x) - 32)]))))) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/);
    }
    #pragma unroll
    for (int i = 0; i < 4; ++i) {
      float broadcast_var = 0x0p+0f/*0.000000e+00*/;
      *(float4*)(sumsq_per_pos + (i * 4)) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
    }
    tl::__sync_thread_partial<3, 64>();
    #pragma unroll
    for (int i_1 = 0; i_1 < 8; ++i_1) {
      tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((i_1 >> 1) * 1024) + (((((i_1 * 64) + ((int)threadIdx.x)) + 96) & 127) * 8)) + 48)])), (&(residual[(((((int64_t)((int)blockIdx.x)) * (int64_t)16384) + ((((int64_t)i_1) >> (int64_t)1) * (int64_t)4096)) + (((((((int64_t)i_1) * (int64_t)64) + ((int64_t)((int)threadIdx.x))) + (int64_t)96) & (int64_t)127) * (int64_t)8))])));
    }
    tl::cp_async_commit();
    #pragma unroll
    for (int i_2 = 0; i_2 < 8; ++i_2) {
      tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((i_2 >> 1) * 1024) + (((((i_2 * 64) + ((int)threadIdx.x)) + 96) & 127) * 8)) + 4144)])), (&(residual[((((((int64_t)((int)blockIdx.x)) * (int64_t)16384) + ((((int64_t)i_2) >> (int64_t)1) * (int64_t)4096)) + (((((((int64_t)i_2) * (int64_t)64) + ((int64_t)((int)threadIdx.x))) + (int64_t)96) & (int64_t)127) * (int64_t)8)) + (int64_t)1024)])));
    }
    tl::cp_async_commit();
    for (int i0_h = 0; i0_h < 2; ++i0_h) {
      tl::cp_async_wait<1>();
      tl::__sync_thread_partial<3, 64>();
      #pragma unroll
      for (int i_3 = 0; i_3 < 8; ++i_3) {
        *(uint4*)(xs_local_cast + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + ((((i0_h * 4096) + (i_3 * 512)) + (((int)threadIdx.x) * 8)) - 208));
        for (int vec = 0; vec < 2; ++vec) {
          float4 __2;
          uint2 v_ = *(uint2*)(xs_local_cast + (vec * 4));
          ((float2*)(&__2))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
          ((float2*)(&__2))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
          *(float4*)(xl + ((i_3 * 8) + (vec * 4))) = __2;
        }
      }
      tl::__sync_thread_partial<3, 64>();
      #pragma unroll
      for (int i_4 = 0; i_4 < 8; ++i_4) {
        tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((i0_h * 4096) + ((i_4 >> 1) * 1024)) + (((((i_4 * 64) + ((int)threadIdx.x)) + 96) & 127) * 8)) + 48)])), (&(residual[(((((((int64_t)((int)blockIdx.x)) * (int64_t)16384) + ((((int64_t)i_4) >> (int64_t)1) * (int64_t)4096)) + (((int64_t)i0_h) * (int64_t)1024)) + (((((((int64_t)i_4) * (int64_t)64) + ((int64_t)((int)threadIdx.x))) + (int64_t)96) & (int64_t)127) * (int64_t)8)) + (int64_t)2048)])));
      }
      tl::cp_async_commit();
      #pragma unroll
      for (int i_5 = 0; i_5 < 4; ++i_5) {
        float broadcast_var_1 = 0x0p+0f/*0.000000e+00*/;
        *(float4*)(ol + (i_5 * 4)) = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
      }
      tl::__sync_thread_partial<3, 64>();
      for (int i_hc = 0; i_hc < 4; ++i_hc) {
        float pre = ((float*)buf_dyn_shmem)[(i_hc + 7256)];
        #pragma unroll
        for (int i_6 = 0; i_6 < 16; ++i_6) {
          ol[i_6] = (ol[i_6] + (pre * xl[((i_hc * 16) + i_6)]));
        }
      }
      #pragma unroll
      for (int i_7 = 0; i_7 < 4; ++i_7) {
        float4 __3;
          float4 v__1 = *(float4*)(ol + (i_7 * 4));
          float4 v__2 = *(float4*)(sumsq_per_pos + (i_7 * 4));
          *(float2*)(&(__3.x)) = tl::fma2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)), *(float2*)(&(v__2.x)));
          *(float2*)(&(__3.z)) = tl::fma2(*(float2*)(&(v__1.z)), *(float2*)(&(v__1.z)), *(float2*)(&(v__2.z)));
        *(float4*)(sumsq_per_pos + (i_7 * 4)) = __3;
        uint2 __4;
        float4 v__3 = *(float4*)(ol + (i_7 * 4));
        (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&v__3))[0]);
        (reinterpret_cast<__nv_bfloat162*>(&__4))[1] = __float22bfloat162_rn(((float2*)(&v__3))[1]);
        *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((((i0_h * 1024) + ((i_7 >> 1) * 512)) + (((int)threadIdx.x) * 8)) + ((i_7 & 1) * 4)) + 7984)) = __4;
      }
    }
    tl::cp_async_wait<1>();
    tl::__sync_thread_partial<3, 64>();
    #pragma unroll
    for (int i_8 = 0; i_8 < 8; ++i_8) {
      *(uint4*)(xs_local_cast_1 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((i_8 * 512) + (((int)threadIdx.x) * 8)) - 208));
      for (int vec_1 = 0; vec_1 < 2; ++vec_1) {
        float4 __5;
        uint2 v__4 = *(uint2*)(xs_local_cast_1 + (vec_1 * 4));
        ((float2*)(&__5))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__4))[0]);
        ((float2*)(&__5))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__4))[1]);
        *(float4*)(xl + ((i_8 * 8) + (vec_1 * 4))) = __5;
      }
    }
    #pragma unroll
    for (int i_9 = 0; i_9 < 4; ++i_9) {
      float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
      *(float4*)(ol + (i_9 * 4)) = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
    }
    for (int i_hc_1 = 0; i_hc_1 < 4; ++i_hc_1) {
      float pre_1 = ((float*)buf_dyn_shmem)[(i_hc_1 + 7256)];
      #pragma unroll
      for (int i_10 = 0; i_10 < 16; ++i_10) {
        ol[i_10] = (ol[i_10] + (pre_1 * xl[((i_hc_1 * 16) + i_10)]));
      }
    }
    #pragma unroll
    for (int i_11 = 0; i_11 < 4; ++i_11) {
      float4 __6;
        float4 v__5 = *(float4*)(ol + (i_11 * 4));
        float4 v__6 = *(float4*)(sumsq_per_pos + (i_11 * 4));
        *(float2*)(&(__6.x)) = tl::fma2(*(float2*)(&(v__5.x)), *(float2*)(&(v__5.x)), *(float2*)(&(v__6.x)));
        *(float2*)(&(__6.z)) = tl::fma2(*(float2*)(&(v__5.z)), *(float2*)(&(v__5.z)), *(float2*)(&(v__6.z)));
      *(float4*)(sumsq_per_pos + (i_11 * 4)) = __6;
      uint2 __7;
      float4 v__7 = *(float4*)(ol + (i_11 * 4));
      (reinterpret_cast<__nv_bfloat162*>(&__7))[0] = __float22bfloat162_rn(((float2*)(&v__7))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__7))[1] = __float22bfloat162_rn(((float2*)(&v__7))[1]);
      *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((((i_11 >> 1) * 512) + (((int)threadIdx.x) * 8)) + ((i_11 & 1) * 4)) + 10032)) = __7;
    }
    tl::cp_async_wait<0>();
    tl::__sync_thread_partial<3, 64>();
    #pragma unroll
    for (int i_12 = 0; i_12 < 8; ++i_12) {
      *(uint4*)(xs_local_cast_2 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((i_12 * 512) + (((int)threadIdx.x) * 8)) + 3888));
      for (int vec_2 = 0; vec_2 < 2; ++vec_2) {
        float4 __8;
        uint2 v__8 = *(uint2*)(xs_local_cast_2 + (vec_2 * 4));
        ((float2*)(&__8))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__8))[0]);
        ((float2*)(&__8))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__8))[1]);
        *(float4*)(xl + ((i_12 * 8) + (vec_2 * 4))) = __8;
      }
    }
    #pragma unroll
    for (int i_13 = 0; i_13 < 4; ++i_13) {
      float broadcast_var_3 = 0x0p+0f/*0.000000e+00*/;
      *(float4*)(ol + (i_13 * 4)) = make_float4(broadcast_var_3, broadcast_var_3, broadcast_var_3, broadcast_var_3);
    }
    for (int i_hc_2 = 0; i_hc_2 < 4; ++i_hc_2) {
      float pre_2 = ((float*)buf_dyn_shmem)[(i_hc_2 + 7256)];
      #pragma unroll
      for (int i_14 = 0; i_14 < 16; ++i_14) {
        ol[i_14] = (ol[i_14] + (pre_2 * xl[((i_hc_2 * 16) + i_14)]));
      }
    }
    #pragma unroll
    for (int i_15 = 0; i_15 < 4; ++i_15) {
      float4 __9;
        float4 v__9 = *(float4*)(ol + (i_15 * 4));
        float4 v__10 = *(float4*)(sumsq_per_pos + (i_15 * 4));
        *(float2*)(&(__9.x)) = tl::fma2(*(float2*)(&(v__9.x)), *(float2*)(&(v__9.x)), *(float2*)(&(v__10.x)));
        *(float2*)(&(__9.z)) = tl::fma2(*(float2*)(&(v__9.z)), *(float2*)(&(v__9.z)), *(float2*)(&(v__10.z)));
      *(float4*)(sumsq_per_pos + (i_15 * 4)) = __9;
      uint2 __10;
      float4 v__11 = *(float4*)(ol + (i_15 * 4));
      (reinterpret_cast<__nv_bfloat162*>(&__10))[0] = __float22bfloat162_rn(((float2*)(&v__11))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__10))[1] = __float22bfloat162_rn(((float2*)(&v__11))[1]);
      *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((((i_15 >> 1) * 512) + (((int)threadIdx.x) * 8)) + ((i_15 & 1) * 4)) + 11056)) = __10;
    }
    sumsq[0] = 0x0p+0f/*0.000000e+00*/;
    #pragma unroll
    for (int rv = 0; rv < 16; ++rv) {
      sumsq[0] = (sumsq[0] + sumsq_per_pos[(((rv & 1) * 8) + (rv >> 1))]);
    }
    tl::__sync_thread_partial<3, 64>();
    sumsq[0] = tl::AllReduce<tl::SumOp, 64, 1, 32, tl::NamedBarrier<64>>::run(sumsq[0], (&(((float*)buf_dyn_shmem)[7192])));
    rsqrt_norm[0] = rsqrtf(((sumsq[0] / 0x1p+12f/*4.096000e+03*/) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
    #pragma unroll
    for (int i_16 = 0; i_16 < 2; ++i_16) {
      tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i_16 * 512) + (((int)threadIdx.x) * 8)) + 12080)])), (&(norm_weight[(((i_16 * 512) + (((int)threadIdx.x) * 8)) - 256)])));
    }
    tl::cp_async_commit();
    #pragma unroll
    for (int i_17 = 0; i_17 < 2; ++i_17) {
      tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i_17 * 512) + (((int)threadIdx.x) * 8)) + 13104)])), (&(norm_weight[(((i_17 * 512) + (((int)threadIdx.x) * 8)) + 768)])));
    }
    tl::cp_async_commit();
    for (int i0_h_1 = 0; i0_h_1 < 2; ++i0_h_1) {
      tl::cp_async_wait<1>();
      tl::__sync_thread_partial<3, 64>();
      #pragma unroll
      for (int i_18 = 0; i_18 < 2; ++i_18) {
        *(uint4*)(w_shared_local_cast_3 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + ((((i0_h_1 * 1024) + (i_18 * 512)) + (((int)threadIdx.x) * 8)) + 12080));
        for (int vec_3 = 0; vec_3 < 2; ++vec_3) {
          float4 __11;
          uint2 v__12 = *(uint2*)(w_shared_local_cast_3 + (vec_3 * 4));
          ((float2*)(&__11))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__12))[0]);
          ((float2*)(&__11))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__12))[1]);
          *(float4*)(w_local + ((i_18 * 8) + (vec_3 * 4))) = __11;
        }
      }
      tl::__sync_thread_partial<3, 64>();
      #pragma unroll
      for (int i_19 = 0; i_19 < 2; ++i_19) {
        tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((i0_h_1 * 1024) + (i_19 * 512)) + (((int)threadIdx.x) * 8)) + 12080)])), (&(norm_weight[((((i0_h_1 * 1024) + (i_19 * 512)) + (((int)threadIdx.x) * 8)) + 1792)])));
      }
      tl::cp_async_commit();
      tl::__sync_thread_partial<3, 64>();
      #pragma unroll
      for (int i_20 = 0; i_20 < 2; ++i_20) {
        *(uint4*)(output_shared_local_cast_4 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + ((((i0_h_1 * 1024) + (i_20 * 512)) + (((int)threadIdx.x) * 8)) + 7984));
        for (int vec_4 = 0; vec_4 < 2; ++vec_4) {
          float4 __12;
            float4 __13;
              float4 __14;
              uint2 v__13 = *(uint2*)(output_shared_local_cast_4 + (vec_4 * 4));
              ((float2*)(&__14))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__13))[0]);
              ((float2*)(&__14))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__13))[1]);
              float4 v__14 = make_float4(rsqrt_norm[0], rsqrt_norm[0], rsqrt_norm[0], rsqrt_norm[0]);
              *(float2*)(&(__13.x)) = tl::mul2(*(float2*)(&(__14.x)), *(float2*)(&(v__14.x)));
              *(float2*)(&(__13.z)) = tl::mul2(*(float2*)(&(__14.z)), *(float2*)(&(v__14.z)));
            float4 v__15 = *(float4*)(w_local + ((i_20 * 8) + (vec_4 * 4)));
            *(float2*)(&(__12.x)) = tl::mul2(*(float2*)(&(__13.x)), *(float2*)(&(v__15.x)));
            *(float2*)(&(__12.z)) = tl::mul2(*(float2*)(&(__13.z)), *(float2*)(&(v__15.z)));
          *(float4*)(ol_1 + ((i_20 * 8) + (vec_4 * 4))) = __12;
        }
      }
      #pragma unroll
      for (int i_21 = 0; i_21 < 2; ++i_21) {
        for (int vec_5 = 0; vec_5 < 2; ++vec_5) {
          uint2 __15;
          float4 v__16 = *(float4*)(ol_1 + ((i_21 * 8) + (vec_5 * 4)));
          (reinterpret_cast<__nv_bfloat162*>(&__15))[0] = __float22bfloat162_rn(((float2*)(&v__16))[0]);
          (reinterpret_cast<__nv_bfloat162*>(&__15))[1] = __float22bfloat162_rn(((float2*)(&v__16))[1]);
          *(uint2*)(layer_input_local_cast_5 + (vec_5 * 4)) = __15;
        }
        *(uint4*)(layer_input + (((((((int64_t)((int)blockIdx.x)) * (int64_t)4096) + (((int64_t)i0_h_1) * (int64_t)1024)) + (((int64_t)i_21) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) - (int64_t)256)) = *(uint4*)(layer_input_local_cast_5 + 0);
      }
    }
    tl::cp_async_wait<1>();
    tl::__sync_thread_partial<3, 64>();
    #pragma unroll
    for (int i_22 = 0; i_22 < 2; ++i_22) {
      *(uint4*)(w_shared_local_cast_6 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((i_22 * 512) + (((int)threadIdx.x) * 8)) + 12080));
      for (int vec_6 = 0; vec_6 < 2; ++vec_6) {
        float4 __16;
        uint2 v__17 = *(uint2*)(w_shared_local_cast_6 + (vec_6 * 4));
        ((float2*)(&__16))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__17))[0]);
        ((float2*)(&__16))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__17))[1]);
        *(float4*)(w_local + ((i_22 * 8) + (vec_6 * 4))) = __16;
      }
    }
    #pragma unroll
    for (int i_23 = 0; i_23 < 2; ++i_23) {
      *(uint4*)(output_shared_local_cast_7 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((i_23 * 512) + (((int)threadIdx.x) * 8)) + 10032));
      for (int vec_7 = 0; vec_7 < 2; ++vec_7) {
        float4 __17;
          float4 __18;
            float4 __19;
            uint2 v__18 = *(uint2*)(output_shared_local_cast_7 + (vec_7 * 4));
            ((float2*)(&__19))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__18))[0]);
            ((float2*)(&__19))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__18))[1]);
            float4 v__19 = make_float4(rsqrt_norm[0], rsqrt_norm[0], rsqrt_norm[0], rsqrt_norm[0]);
            *(float2*)(&(__18.x)) = tl::mul2(*(float2*)(&(__19.x)), *(float2*)(&(v__19.x)));
            *(float2*)(&(__18.z)) = tl::mul2(*(float2*)(&(__19.z)), *(float2*)(&(v__19.z)));
          float4 v__20 = *(float4*)(w_local + ((i_23 * 8) + (vec_7 * 4)));
          *(float2*)(&(__17.x)) = tl::mul2(*(float2*)(&(__18.x)), *(float2*)(&(v__20.x)));
          *(float2*)(&(__17.z)) = tl::mul2(*(float2*)(&(__18.z)), *(float2*)(&(v__20.z)));
        *(float4*)(ol_1 + ((i_23 * 8) + (vec_7 * 4))) = __17;
      }
    }
    #pragma unroll
    for (int i_24 = 0; i_24 < 2; ++i_24) {
      for (int vec_8 = 0; vec_8 < 2; ++vec_8) {
        uint2 __20;
        float4 v__21 = *(float4*)(ol_1 + ((i_24 * 8) + (vec_8 * 4)));
        (reinterpret_cast<__nv_bfloat162*>(&__20))[0] = __float22bfloat162_rn(((float2*)(&v__21))[0]);
        (reinterpret_cast<__nv_bfloat162*>(&__20))[1] = __float22bfloat162_rn(((float2*)(&v__21))[1]);
        *(uint2*)(layer_input_local_cast_8 + (vec_8 * 4)) = __20;
      }
      *(uint4*)(layer_input + ((((((int64_t)((int)blockIdx.x)) * (int64_t)4096) + (((int64_t)i_24) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)1792)) = *(uint4*)(layer_input_local_cast_8 + 0);
    }
    tl::cp_async_wait<0>();
    tl::__sync_thread_partial<3, 64>();
    #pragma unroll
    for (int i_25 = 0; i_25 < 2; ++i_25) {
      *(uint4*)(w_shared_local_cast_9 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((i_25 * 512) + (((int)threadIdx.x) * 8)) + 13104));
      for (int vec_9 = 0; vec_9 < 2; ++vec_9) {
        float4 __21;
        uint2 v__22 = *(uint2*)(w_shared_local_cast_9 + (vec_9 * 4));
        ((float2*)(&__21))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__22))[0]);
        ((float2*)(&__21))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__22))[1]);
        *(float4*)(w_local + ((i_25 * 8) + (vec_9 * 4))) = __21;
      }
    }
    #pragma unroll
    for (int i_26 = 0; i_26 < 2; ++i_26) {
      *(uint4*)(output_shared_local_cast_10 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((i_26 * 512) + (((int)threadIdx.x) * 8)) + 11056));
      for (int vec_10 = 0; vec_10 < 2; ++vec_10) {
        float4 __22;
          float4 __23;
            float4 __24;
            uint2 v__23 = *(uint2*)(output_shared_local_cast_10 + (vec_10 * 4));
            ((float2*)(&__24))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__23))[0]);
            ((float2*)(&__24))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__23))[1]);
            float4 v__24 = make_float4(rsqrt_norm[0], rsqrt_norm[0], rsqrt_norm[0], rsqrt_norm[0]);
            *(float2*)(&(__23.x)) = tl::mul2(*(float2*)(&(__24.x)), *(float2*)(&(v__24.x)));
            *(float2*)(&(__23.z)) = tl::mul2(*(float2*)(&(__24.z)), *(float2*)(&(v__24.z)));
          float4 v__25 = *(float4*)(w_local + ((i_26 * 8) + (vec_10 * 4)));
          *(float2*)(&(__22.x)) = tl::mul2(*(float2*)(&(__23.x)), *(float2*)(&(v__25.x)));
          *(float2*)(&(__22.z)) = tl::mul2(*(float2*)(&(__23.z)), *(float2*)(&(v__25.z)));
        *(float4*)(ol_1 + ((i_26 * 8) + (vec_10 * 4))) = __22;
      }
    }
    #pragma unroll
    for (int i_27 = 0; i_27 < 2; ++i_27) {
      for (int vec_11 = 0; vec_11 < 2; ++vec_11) {
        uint2 __25;
        float4 v__26 = *(float4*)(ol_1 + ((i_27 * 8) + (vec_11 * 4)));
        (reinterpret_cast<__nv_bfloat162*>(&__25))[0] = __float22bfloat162_rn(((float2*)(&v__26))[0]);
        (reinterpret_cast<__nv_bfloat162*>(&__25))[1] = __float22bfloat162_rn(((float2*)(&v__26))[1]);
        *(uint2*)(layer_input_local_cast_11 + (vec_11 * 4)) = __25;
      }
      *(uint4*)(layer_input + ((((((int64_t)((int)blockIdx.x)) * (int64_t)4096) + (((int64_t)i_27) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)2816)) = *(uint4*)(layer_input_local_cast_11 + 0);
    }
  }
  cudaTriggerProgrammaticLaunchCompletion();
}
